# Generated by Django 5.2.3 on 2025-07-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_alter_articlecomment_answer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecomment',
            table='t_article_comment',
        ),
        migrations.AlterModelTable(
            name='question',
            table='t_question',
        ),
    ]
