### 测试增加文章收藏
POST http://localhost:8000/api/v1/collect/add/1/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzNTUwNzM4Ljg3NzA1NX0.vAl-qqZw6ES9ArANL5kZ6LXqXjKW4c6jxShs0kpavRs


### 测试取消文章收藏
DELETE http://localhost:8000/api/v1/collect/delete/1/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzNTUwNzM4Ljg3NzA1NX0.vAl-qqZw6ES9ArANL5kZ6LXqXjKW4c6jxShs0kpavRs

### 测试获取文章收藏列表
GET http://localhost:8000/api/v1/collect/list/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzNTUwNzM4Ljg3NzA1NX0.vAl-qqZw6ES9ArANL5kZ6LXqXjKW4c6jxShs0kpavRs