### 测试个人文章评论发布
POST http://localhost:8000/api/v1/question/comment/add/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzMzcxMjI2LjQ5MDMyMDd9.HxsGBlTtRKMcQkGcPG-Ntzr5rovPbBCCDcSp0Qpm-zM

{
    "comment" : "测试",
    "article" : 1    
}

### 测试个人文章评论删除
DELETE http://localhost:8000/api/v1/question/comment/delete/2/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzMzcxMjI2LjQ5MDMyMDd9.HxsGBlTtRKMcQkGcPG-Ntzr5rovPbBCCDcSp0Qpm-zM

### 测试获取个人文章评论列表 （没开发好）
GET http://localhost:8000/api/v1/question/comment/list/2/


### 测试个人文章评论回复
POST http://localhost:8000/api/v1/question/comment/answer/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzMzcxMjI2LjQ5MDMyMDd9.HxsGBlTtRKMcQkGcPG-Ntzr5rovPbBCCDcSp0Qpm-zM

{
    "comment" : "世界，你好你好",
    "article" : 1,
    "answer" : 1 
}

### 测试问题反馈 (未开发)
POST POST http://localhost:8000/api/v1/question/add/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE2ODg4ODg4ODg4IiwiZXhwIjoxNzUzNTQ5NDQxLjk0MTA5MzR9.oTiixEFyVmzWZL3WQlWubEbaBFPJbZnAu-NzfH6ewcA

{
    "comment" : "测试问题反馈"
}