# Generated by Django 5.2.3 on 2025-07-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0007_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(blank=True, max_length=144, null=True, verbose_name='个人简介')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=10, null=True, verbose_name='地址')),
                ('sex', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人主页信息',
                'db_table': 't_personal',
            },
        ),
    ]
