# Generated by Django 5.2.3 on 2025-09-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={},
        ),
    ]
