# Generated by Django 5.2.3 on 2025-07-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_app', '0003_alter_article_content'),
        ('user_app', '0007_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'db_table': 't_collect_Article',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
