# Generated by Django 5.2.3 on 2025-07-25 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='收藏时间'),
            preserve_default=False,
        ),
    ]
