# Generated by Django 5.2.3 on 2025-07-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_email_alter_user_nick_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='_password',
            field=models.CharField(default=1, max_length=512, verbose_name='加密密码'),
            preserve_default=False,
        ),
    ]
