# Generated by Django 5.2.3 on 2025-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_password_user__password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_password',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='加密密码'),
        ),
    ]
