# Generated by Django 5.2.3 on 2025-07-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息'},
        ),
    ]
