# Generated by Django 5.2.3 on 2025-07-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likearticle',
            table='t_like_article',
        ),
    ]
