# Generated by Django 5.2.3 on 2025-07-26 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_app', '0002_alter_likearticle_table'),
        ('user_app', '0007_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='likearticle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间'),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间'),
        ),
        migrations.AlterField(
            model_name='likearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user', verbose_name='点赞用户'),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user', verbose_name='点赞用户'),
        ),
    ]
