# Generated by Django 5.2.3 on 2025-09-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_app', '0003_likearticle_created_at_likecomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likearticle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likecomment',
            options={},
        ),
    ]
