# Generated by Django 5.2.3 on 2025-07-20 06:06

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, '学习'), (1, '生活'), (2, '其他')], unique=True, verbose_name='分类名称')),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, verbose_name='标签名称')),
            ],
            options={
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', tinymce.models.HTMLField()),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '发布')], default=0, verbose_name='文章状态')),
                ('type', models.IntegerField(choices=[(0, '原创'), (1, '转载')], default=0, verbose_name='文章类型')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐文章')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acticles', to='user_app.user', verbose_name='作者')),
                ('cagegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog_app.category', verbose_name='文章分类')),
                ('tags', models.ManyToManyField(related_name='articles', to='blog_app.tag', verbose_name='文章标签')),
            ],
            options={
                'db_table': 't_article',
                'ordering': ['-created_at'],
            },
        ),
    ]
