# Generated by Django 5.2.3 on 2025-07-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cagegory',
            new_name='category',
        ),
    ]
